{{- if not .Values.config.overrideConfigExistingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vouch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vouch.name" . }}
    helm.sh/chart: {{ include "vouch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if not .Values.config.vouch.existingSecret }}
  domains: {{ join "," .Values.config.vouch.domains | b64enc | quote }}
  whiteList: {{ join "," .Values.config.vouch.whiteList | b64enc | quote }}
  jwtSecret: {{ .Values.config.vouch.jwt.secret | b64enc | quote }}
  {{- end }}
  {{- if not .Values.config.oauth.existingSecret }}
  provider: {{ .Values.config.oauth.provider | b64enc | quote }}
  clientId: {{ .Values.config.oauth.clientId | b64enc | quote }}
  clientSecret: {{ .Values.config.oauth.clientSecret | b64enc | quote }}
  authUrl: {{ .Values.config.oauth.authUrl | b64enc | quote }}
  tokenUrl: {{ .Values.config.oauth.tokenUrl | b64enc | quote }}
  userInfoUrl: {{ .Values.config.oauth.userInfoUrl | b64enc | quote }}
  callbackUrls: {{ join "," .Values.config.oauth.callbackUrls | b64enc | quote }}
  preferredDomain: {{ .Values.config.oauth.preferredDomain | b64enc | quote }}
  {{- end }}
{{- end }}
