---
apiVersion: v2
type: application
name: vouch
description: An SSO and OAuth login solution for nginx using the auth_request module.
icon: https://avatars0.githubusercontent.com/u/45102943?s=200&v=4
home: https://github.com/vouch/vouch-proxy/
sources:
  - https://github.com/vouch/vouch-proxy/

keywords:
  - nginx
  - auth
  - oauth2
  - authentication
  - nginx-proxy
  - sso
  - sso-login

version: 4.0.1

# renovate: image=quay.io/vouch/vouch-proxy
appVersion: "0.39"

maintainers:
  - name: jessebot
    email: jessebot@linux.com
